# Generated by Django 3.0.2 on 2020-04-05 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manage_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='project_experience',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Taught_By',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Project_experience')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Enroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Create',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Assign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Course')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_app.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='admin_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='manage_app.Admin'),
        ),
        migrations.AddField(
            model_name='course',
            name='project',
            field=models.ManyToManyField(through='manage_app.Course_Assign', to='manage_app.Project'),
        ),
        migrations.AddField(
            model_name='course',
            name='student',
            field=models.ManyToManyField(through='manage_app.Student_Enroll', to='manage_app.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='create',
            field=models.ManyToManyField(related_name='created', through='manage_app.Student_Create', to='manage_app.Student'),
        ),
        migrations.AddField(
            model_name='group',
            name='join',
            field=models.ManyToManyField(related_name='Join_group', through='manage_app.Student_Join', to='manage_app.Student'),
        ),
        migrations.AddField(
            model_name='project_experience',
            name='student',
            field=models.ManyToManyField(through='manage_app.Student_experience', to='manage_app.Student'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='course',
            field=models.ManyToManyField(through='manage_app.Taught_By', to='manage_app.Course'),
        ),
    ]
