# Generated by Django 3.0.2 on 2020-04-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0002_auto_20200406_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
    ]
