# Generated by Django 3.0.2 on 2020-04-06 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_app', '0003_auto_20200406_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='admin_id',
        ),
    ]
